language: ruby
rvm:
- 2.0.0
before_install:
- gem install sass
- npm install
- npm install -g bower
- bower install
before_script:
- bundle exec rake travis:decrypt_config
script:
- gulp build
after_success:
- bundle exec rake travis:deploy
env:
  global:
  - secure: Z8V/n1Y4D1rsY07HZzhgZ/6chfI1bwiKZT9qwxT5lEk8KaD6OZhcEga8MZ7sk2HJvD+vOk7qB9uV6lPlUlz5CjO7FCip1VO+kj1HSkBqLr7HbY0KbGjrFgCO7F87aw1LXtC2gR4jVt70VWOy7Bp4YiLOKBRF4J4FkMLrxVvR1Ak=
notifications:
  slack:
    secure: dZhvXPgzd7c+qJTBe/t4CbG6j8S76cGaDHtDYJ1XMLWIOJ5ereR7SxEo++3U9aDigPk00y0b6N3QnS+Hk79y3DgGYL2DEdhghPr4T1j6JhwDR/ZcJXcoSolO6ikmOhGnauUSH6g9xbW99jyFRzCbnkSmv2VpCCyr1JFUmZYBJnk=
